import type {
  ButtonBinding,
  CallEvent,
  ChatMessage,
  Employee,
  ErrorLog,
  IikoState,
  NewButtonSignal,
  Service,
  SettingsState,
  SystemMode,
  TableAssignment,
  TableItem,
  TechLog,
} from '../types'

const minutesAgo = (minutes: number) => new Date(Date.now() - minutes * 60_000).toISOString()

const createTables = (): TableItem[] =>
  Array.from({ length: 20 }, (_, index) => {
    const tableNumber = index + 1
    const zones: TableItem['zone'][] = ['Зал', 'Веранда', 'VIP']

    return {
      id: `table-${tableNumber}`,
      name: `Стол ${tableNumber}`,
      zone: zones[index % zones.length],
      is_active: true,
    }
  })

export const seedServices: Service[] = [
  { id: 'svc-waiter', name: 'Официант', assigned_role: 'waiter', is_active: true },
  { id: 'svc-hookah', name: 'Кальян', assigned_role: 'hookah', is_active: true },
]

export const seedTables = createTables()

export const seedEmployees: Employee[] = [
  { id: 'emp-ivan', full_name: 'Иван П.', role: 'waiter', max_user_id: 'max_ivan', is_active: true },
  { id: 'emp-anton', full_name: 'Антон С.', role: 'waiter', max_user_id: 'max_anton', is_active: true },
  { id: 'emp-maria', full_name: 'Мария К.', role: 'waiter', max_user_id: 'max_maria', is_active: true },
  { id: 'emp-sergey', full_name: 'Сергей К.', role: 'hookah', max_user_id: 'max_sergey', is_active: true },
  { id: 'emp-denis', full_name: 'Денис Л.', role: 'hookah', max_user_id: 'max_denis', is_active: true },
  { id: 'emp-admin', full_name: 'Администратор', role: 'admin', max_user_id: 'max_admin', is_active: true },
]

export const seedBindings: ButtonBinding[] = [
  { radio_button_id: 'RB-W-1003', table_id: 'table-3', service_id: 'svc-waiter', is_active: true, created_at: minutesAgo(600) },
  { radio_button_id: 'RB-W-1004', table_id: 'table-4', service_id: 'svc-waiter', is_active: true, created_at: minutesAgo(595) },
  { radio_button_id: 'RB-W-1005', table_id: 'table-5', service_id: 'svc-waiter', is_active: true, created_at: minutesAgo(590) },
  { radio_button_id: 'RB-W-1006', table_id: 'table-6', service_id: 'svc-waiter', is_active: true, created_at: minutesAgo(585) },
  { radio_button_id: 'RB-W-1012', table_id: 'table-12', service_id: 'svc-waiter', is_active: true, created_at: minutesAgo(580) },
  { radio_button_id: 'RB-W-1015', table_id: 'table-15', service_id: 'svc-waiter', is_active: true, created_at: minutesAgo(575) },
  { radio_button_id: 'RB-W-1018', table_id: 'table-18', service_id: 'svc-waiter', is_active: true, created_at: minutesAgo(570) },
  { radio_button_id: 'RB-H-2007', table_id: 'table-7', service_id: 'svc-hookah', is_active: true, created_at: minutesAgo(565) },
  { radio_button_id: 'RB-H-2010', table_id: 'table-10', service_id: 'svc-hookah', is_active: true, created_at: minutesAgo(560) },
  { radio_button_id: 'RB-H-2014', table_id: 'table-14', service_id: 'svc-hookah', is_active: true, created_at: minutesAgo(555) },
]

export const seedCallEvents: CallEvent[] = [
  {
    event_id: 'call-001',
    client_device_id: 'device-hall-1',
    radio_button_id: 'RB-W-1003',
    table_id: 'table-3',
    service_id: 'svc-waiter',
    status: 'confirmed',
    received_at: minutesAgo(46),
    routed_at: minutesAgo(46),
    notified_at: minutesAgo(45),
    confirmed_at: minutesAgo(44),
    responded_by_employee_id: 'emp-ivan',
    raw_signal: '{"radio":"RB-W-1003","device":"device-hall-1","strength":88}',
  },
  {
    event_id: 'call-002',
    client_device_id: 'device-vip-1',
    radio_button_id: 'RB-W-1012',
    table_id: 'table-12',
    service_id: 'svc-waiter',
    status: 'confirmed',
    received_at: minutesAgo(34),
    routed_at: minutesAgo(34),
    notified_at: minutesAgo(33),
    confirmed_at: minutesAgo(31),
    responded_by_employee_id: 'emp-maria',
    raw_signal: '{"radio":"RB-W-1012","device":"device-vip-1","strength":81}',
  },
  {
    event_id: 'call-003',
    client_device_id: 'device-hookah-1',
    radio_button_id: 'RB-H-2007',
    table_id: 'table-7',
    service_id: 'svc-hookah',
    status: 'confirmed',
    received_at: minutesAgo(28),
    routed_at: minutesAgo(28),
    notified_at: minutesAgo(27),
    confirmed_at: minutesAgo(24),
    responded_by_employee_id: 'emp-sergey',
    raw_signal: '{"radio":"RB-H-2007","device":"device-hookah-1","strength":92}',
  },
  {
    event_id: 'call-004',
    client_device_id: 'device-hall-2',
    radio_button_id: 'RB-W-1004',
    table_id: 'table-4',
    service_id: 'svc-waiter',
    status: 'confirmed',
    received_at: minutesAgo(78),
    routed_at: minutesAgo(78),
    notified_at: minutesAgo(77),
    confirmed_at: minutesAgo(75),
    responded_by_employee_id: 'emp-anton',
    raw_signal: '{"radio":"RB-W-1004","device":"device-hall-2","strength":86}',
  },
  {
    event_id: 'call-005',
    client_device_id: 'device-veranda-2',
    radio_button_id: 'RB-W-1015',
    table_id: 'table-15',
    service_id: 'svc-waiter',
    status: 'confirmed',
    received_at: minutesAgo(120),
    routed_at: minutesAgo(120),
    notified_at: minutesAgo(119),
    confirmed_at: minutesAgo(116),
    responded_by_employee_id: 'emp-ivan',
    raw_signal: '{"radio":"RB-W-1015","device":"device-veranda-2","strength":79}',
  },
  {
    event_id: 'call-006',
    client_device_id: 'device-hall-1',
    radio_button_id: 'RB-W-1003',
    table_id: 'table-3',
    service_id: 'svc-waiter',
    status: 'notified',
    received_at: minutesAgo(8),
    routed_at: minutesAgo(8),
    notified_at: minutesAgo(7),
    raw_signal: '{"radio":"RB-W-1003","device":"device-hall-1","strength":90}',
    note: 'Повторный вызов действующего столика',
  },
  {
    event_id: 'call-007',
    client_device_id: 'device-hookah-1',
    radio_button_id: 'RB-H-2007',
    table_id: 'table-7',
    service_id: 'svc-hookah',
    status: 'notified',
    received_at: minutesAgo(6),
    routed_at: minutesAgo(6),
    notified_at: minutesAgo(5),
    raw_signal: '{"radio":"RB-H-2007","device":"device-hookah-1","strength":91}',
  },
  {
    event_id: 'call-008',
    client_device_id: 'device-veranda-3',
    radio_button_id: 'RB-W-1018',
    table_id: 'table-18',
    service_id: 'svc-waiter',
    status: 'notified',
    received_at: minutesAgo(4),
    routed_at: minutesAgo(4),
    notified_at: minutesAgo(4),
    raw_signal: '{"radio":"RB-W-1018","device":"device-veranda-3","strength":87}',
  },
  {
    event_id: 'call-009',
    client_device_id: 'device-lobby-1',
    radio_button_id: 'RB-9999',
    table_id: null,
    service_id: null,
    status: 'unknown_button',
    received_at: minutesAgo(18),
    raw_signal: '{"radio":"RB-9999","device":"device-lobby-1","strength":52}',
    note: 'Кнопка отсутствует в whitelist',
  },
  {
    event_id: 'call-010',
    client_device_id: 'device-hall-2',
    radio_button_id: 'RB-W-1006',
    table_id: 'table-6',
    service_id: 'svc-waiter',
    status: 'error',
    received_at: minutesAgo(14),
    routed_at: minutesAgo(14),
    notified_at: minutesAgo(13),
    raw_signal: '{"radio":"RB-W-1006","device":"device-hall-2","strength":84}',
    note: 'IIKO не подтвердил check state',
  },
  {
    event_id: 'call-011',
    client_device_id: 'device-lobby-2',
    radio_button_id: '???',
    table_id: null,
    service_id: null,
    status: 'invalid_signal',
    received_at: minutesAgo(11),
    raw_signal: '{"radio":"???","payload":"corrupted"}',
  },
  {
    event_id: 'call-012',
    client_device_id: 'device-lobby-2',
    radio_button_id: '',
    table_id: null,
    service_id: null,
    status: 'invalid_signal',
    received_at: minutesAgo(2),
    raw_signal: '{"device":"device-lobby-2","payload":"missing-radio"}',
  },
]

export const seedAssignments: TableAssignment[] = [
  {
    id: 'assign-001',
    table_id: 'table-3',
    assigned_employee_id: 'emp-ivan',
    assignment_scope: 'waiter',
    status: 'active',
    assigned_at: minutesAgo(44),
    iiko_check_id: 'CHK-3003',
  },
  {
    id: 'assign-002',
    table_id: 'table-12',
    assigned_employee_id: 'emp-maria',
    assignment_scope: 'waiter',
    status: 'active',
    assigned_at: minutesAgo(31),
    iiko_check_id: 'CHK-3012',
  },
  {
    id: 'assign-003',
    table_id: 'table-7',
    assigned_employee_id: 'emp-sergey',
    assignment_scope: 'hookah',
    status: 'active',
    assigned_at: minutesAgo(24),
  },
  {
    id: 'assign-004',
    table_id: 'table-4',
    assigned_employee_id: 'emp-anton',
    assignment_scope: 'waiter',
    status: 'released',
    assigned_at: minutesAgo(75),
    released_at: minutesAgo(35),
    release_reason: 'check_closed',
    iiko_check_id: 'CHK-3004',
  },
  {
    id: 'assign-005',
    table_id: 'table-15',
    assigned_employee_id: 'emp-ivan',
    assignment_scope: 'waiter',
    status: 'released',
    assigned_at: minutesAgo(116),
    released_at: minutesAgo(60),
    release_reason: 'manual_reset',
    iiko_check_id: 'CHK-3015',
  },
]

export const seedChatMessages: ChatMessage[] = [
  {
    id: 'msg-001',
    event_id: 'call-001',
    table_id: 'table-3',
    service_id: 'svc-waiter',
    state: 'closed',
    created_at: minutesAgo(45),
    responded_by_employee_id: 'emp-ivan',
    text: 'Стол 3 вызывает официанта',
  },
  {
    id: 'msg-002',
    event_id: 'call-002',
    table_id: 'table-12',
    service_id: 'svc-waiter',
    state: 'closed',
    created_at: minutesAgo(33),
    responded_by_employee_id: 'emp-maria',
    text: 'Стол 12 вызывает официанта',
  },
  {
    id: 'msg-003',
    event_id: 'call-003',
    table_id: 'table-7',
    service_id: 'svc-hookah',
    state: 'closed',
    created_at: minutesAgo(27),
    responded_by_employee_id: 'emp-sergey',
    text: 'Стол 7 вызывает кальянщика',
  },
  {
    id: 'msg-004',
    event_id: 'call-004',
    table_id: 'table-4',
    service_id: 'svc-waiter',
    state: 'closed',
    created_at: minutesAgo(77),
    responded_by_employee_id: 'emp-anton',
    text: 'Стол 4 вызывает официанта',
  },
  {
    id: 'msg-005',
    event_id: 'call-005',
    table_id: 'table-15',
    service_id: 'svc-waiter',
    state: 'closed',
    created_at: minutesAgo(119),
    responded_by_employee_id: 'emp-ivan',
    text: 'Стол 15 вызывает официанта',
  },
  {
    id: 'msg-006',
    event_id: 'call-006',
    table_id: 'table-3',
    service_id: 'svc-waiter',
    state: 'open',
    created_at: minutesAgo(7),
    text: 'Стол 3 повторно вызывает официанта',
  },
  {
    id: 'msg-007',
    event_id: 'call-007',
    table_id: 'table-7',
    service_id: 'svc-hookah',
    state: 'open',
    created_at: minutesAgo(5),
    text: 'Стол 7 вызывает кальянщика',
  },
  {
    id: 'msg-008',
    event_id: 'call-008',
    table_id: 'table-18',
    service_id: 'svc-waiter',
    state: 'open',
    created_at: minutesAgo(4),
    text: 'Стол 18 вызывает официанта',
  },
]

export const seedNewButtons: NewButtonSignal[] = [
  {
    radio_button_id: 'RB-8801',
    first_seen_at: minutesAgo(22),
    last_seen_at: minutesAgo(3),
    samples_count: 3,
    last_client_device_id: 'device-veranda-unknown',
    raw_signal: '{"radio":"RB-8801","device":"device-veranda-unknown","strength":69}',
  },
  {
    radio_button_id: 'RB-8802',
    first_seen_at: minutesAgo(41),
    last_seen_at: minutesAgo(12),
    samples_count: 2,
    last_client_device_id: 'device-vip-unknown',
    raw_signal: '{"radio":"RB-8802","device":"device-vip-unknown","strength":73}',
  },
]

export const seedTechLogs: TechLog[] = [
  { id: 'tech-001', scope: 'system', level: 'success', message: 'Система инициализирована', created_at: minutesAgo(180) },
  { id: 'tech-002', scope: 'bot', level: 'warning', message: 'suppressed duplicate: RB-W-1003 в окне 2 секунд', created_at: minutesAgo(9) },
  { id: 'tech-003', scope: 'simulator', level: 'info', message: 'Симулятор MAX-чата готов к обработке новых вызовов', created_at: minutesAgo(5) },
]

export const seedErrorLogs: ErrorLog[] = [
  {
    id: 'err-001',
    component: 'iiko',
    level: 'error',
    message: 'Не удалось получить check state для CHK-3006, событие оставлено в статусе error',
    created_at: minutesAgo(13),
    related_event_id: 'call-010',
  },
  {
    id: 'err-002',
    component: 'bot',
    level: 'warning',
    message: 'Получен неизвестный radio_button_id RB-9999 в рабочем режиме',
    created_at: minutesAgo(18),
    related_event_id: 'call-009',
  },
  {
    id: 'err-003',
    component: 'client',
    level: 'warning',
    message: 'Локальный симулятор отбросил пустой payload без radio_button_id',
    created_at: minutesAgo(2),
    related_event_id: 'call-012',
  },
  {
    id: 'err-004',
    component: 'backend',
    level: 'error',
    message: 'Сервис обработки вернул 503 при попытке обогатить сигнал метаданными стола',
    created_at: minutesAgo(52),
  },
]

export const seedIikoState: IikoState = {
  token: 'demo-iiko-token-001',
  status: 'connected',
  last_sync_at: minutesAgo(1),
  event_logs: [
    { id: 'iiko-001', type: 'sync', message: 'Подключение к IIKO активно', created_at: minutesAgo(180) },
    {
      id: 'iiko-002',
      type: 'check_closed',
      message: 'Чек CHK-3004 закрыт, закрепление официанта по столу 4 снято',
      created_at: minutesAgo(35),
      table_id: 'table-4',
      assignment_id: 'assign-004',
    },
    { id: 'iiko-003', type: 'warning', message: 'IIKO ответил с задержкой 1800ms', created_at: minutesAgo(15) },
  ],
}

export const seedSettings: SettingsState = {
  restaurant_name: 'QWIK.PRO Demo Cafe',
  timezone: 'Asia/Omsk',
  support_phone: '+7 (999) 100-20-30',
}

export const createInitialState = () => ({
  systemMode: 'work' as SystemMode,
  services: seedServices,
  tables: seedTables,
  employees: seedEmployees,
  bindings: seedBindings,
  callEvents: seedCallEvents,
  assignments: seedAssignments,
  chatMessages: seedChatMessages,
  newButtons: seedNewButtons,
  techLogs: seedTechLogs,
  errorLogs: seedErrorLogs,
  iiko: seedIikoState,
  settings: seedSettings,
  selectedChatEmployeeId: 'emp-ivan',
})
